# Intro to pandas and numpy

[Youtube Link](https://www.youtube.com/watch?v=CMEWVn1uZpQ&t=6120)

In [323]:
import os 
import sys
import time
print(sys.platform)             # e.g. 'win32', 'linux', 'darwin'
os.getcwd()                   # Get current working directory
print(os.system('mkdir new_folder'))
print(os.system('ls'))
time.sleep(2)                # Sleep for 2 seconds
print(os.system('rm -r new_folder'))  # Remove the folder created
print(os.system('ls')) 
os.chdir(f'{os.getcwd()}/data')
os.system('echo "name, last_name, date" > hello.txt')              # List files in the current directory
for i in range(100):
  date = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
  nme = "Ivan"
  last_name = "Gomez"
  os.system(f'echo "{nme}, {last_name}, {date}" >> hello.txt')  # Append to the file
  time.sleep(0.1)
os.system('ls -l hello.txt')  #
os.chdir('..')  # Change back to the parent directory

darwin
0
data
intro_to_pandas_and_numpy.ipynb
new_folder
python_review.ipynb
0
0
data
intro_to_pandas_and_numpy.ipynb
python_review.ipynb
0
-rw-r--r--@ 1 ivandavidgomezsilva  staff  3322 Aug  3 22:26 hello.txt

In [324]:
os.listdir('.')  # List files in the current directory

['intro_to_pandas_and_numpy.ipynb', 'python_review.ipynb', 'data']

In [325]:
os.makedirs('data/subfolder1/subfolder2', exist_ok=True)  # Create nested directories

## Pandas

It is a powerful library for data manipulation and analysis, built on top of NumPy.
Clean data, manipulate data, and analyze data.
It is like a spreadsheet in Python.

Advantages of Pandas vs Excel:
- Handles larger datasets efficiently.
- Complex data manipulations are easier.
- Automation and reproducibility with scripts.
- Cross-platform compatibility.

### Pandas terminology

| Excel | Pandas |
|-------|--------|
| Worksheet | DataFrame |
| Column | Series |
| Row heading | Index |
| Row | Row |
| Empty cell | NaN (Not a Number) |

## How to Create a DataFrame

1. With arrays

```python
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```
- The first row becomes the column names.
- The rest of the rows become the data in the DataFrame.
2. With dictionaries

```python
data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}
```
- The Keys of the dictionary become the column names.
- The values become the data in the DataFrame.
  
3. With csv files

In [326]:
import pandas as pd
import numpy as np

In [327]:
# Option 1: Creating a DataFrame from a NumPy array
array = np.array([['Hello', 'World'], [1, 2], [3.0, 4.0], 
          [True, False], [None, None]])
df = pd.DataFrame(array[1:], columns=array[0])
df

  Hello  World
0     1      2
1   3.0    4.0
2  True  False
3  None   None

In [328]:
# Option 2: Creating a DataFrame from a Dictionary
dictionary = {
  'Hello': [1, 3.0, True, None],
  'World': [2, 4.0, False, None]
}
df = pd.DataFrame(dictionary)
df

  Hello  World
0     1      2
1   3.0    4.0
2  True  False
3  None   None

In [329]:
# Option 3: Reading from a CSV file
df = pd.read_csv('data/helloWorld.csv')
df

  Hello  World    numbers  boolean  null
0     1      2   3.537880     True   NaN
1   3.0    4.0   5.012346    False   NaN
2  True  False  41.987654    False   NaN
3   NaN    NaN  30.456357     True   NaN

In [330]:
df.dtypes

Hello       object
World       object
numbers    float64
boolean       bool
null       float64
dtype: object

In [331]:
df.describe()

         numbers  null
count   4.000000   0.0
mean   20.248559   NaN
std    19.045353   NaN
min     3.537880   NaN
25%     4.643729   NaN
50%    17.734351   NaN
75%    33.339181   NaN
max    41.987654   NaN

In [332]:
# Scraping tables from a website
import requests
# Scraping tables from a website
url = 'https://www.britannica.com/topic/list-of-countries-1993160'
headers = {'User-Agent': 'Mozilla/5.0'}
response = requests.get(url, headers=headers)
tables = pd.read_html(response.text)
geography_df = tables[0]
geography_df['geographical region'].astype(str) 
geography_df['name'].astype(str)  
geography_df

/var/folders/dh/cyk127ld03gf26jbxvh7s4kc0000gn/T/ipykernel_5192/2888255794.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

                   name geographical region
0           Afghanistan                Asia
1               Albania              Europe
2               Algeria              Africa
3        American Samoa             Oceania
4               Andorra              Europe
5                Angola              Africa
6              Anguilla           Caribbean
7   Antigua and Barbuda           Caribbean
8             Argentina       South America
9               Armenia                Asia
10                Aruba           Caribbean
11            Australia             Oceania
12              Austria              Europe
13           Azerbaijan                Asia
14                  NaN                 NaN

In [333]:
geography_df.tail()

          name geographical region
10       Aruba           Caribbean
11   Australia             Oceania
12     Austria              Europe
13  Azerbaijan                Asia
14         NaN                 NaN

In [334]:
geography_df.head()

             name geographical region
0     Afghanistan                Asia
1         Albania              Europe
2         Algeria              Africa
3  American Samoa             Oceania
4         Andorra              Europe

In [335]:
geography_df.shape

(15, 2)

## Attributes, methods, and functions

### 1. Attributes

In [336]:
geography_df.shape

(15, 2)

In [337]:
geography_df.index

RangeIndex(start=0, stop=15, step=1)

In [338]:
geography_df.columns

Index(['name', 'geographical region'], dtype='object')

In [339]:
geography_df

                   name geographical region
0           Afghanistan                Asia
1               Albania              Europe
2               Algeria              Africa
3        American Samoa             Oceania
4               Andorra              Europe
5                Angola              Africa
6              Anguilla           Caribbean
7   Antigua and Barbuda           Caribbean
8             Argentina       South America
9               Armenia                Asia
10                Aruba           Caribbean
11            Australia             Oceania
12              Austria              Europe
13           Azerbaijan                Asia
14                  NaN                 NaN

In [340]:
geography_df.dtypes

name                   object
geographical region    object
dtype: object

### 2. Methods

In [341]:
geography_df.head()

             name geographical region
0     Afghanistan                Asia
1         Albania              Europe
2         Algeria              Africa
3  American Samoa             Oceania
4         Andorra              Europe

In [342]:
geography_df.describe()

               name geographical region
count            14                  14
unique           14                   6
top     Afghanistan                Asia
freq              1                   3

In [343]:
geography_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 14 non-null     object
 1   geographical region  14 non-null     object
dtypes: object(2)
memory usage: 372.0+ bytes

### 3. Functions

In [344]:
len(geography_df)

15

In [345]:
max(geography_df)

'name'

In [346]:
max(geography_df.index)

14

In [347]:
# Rounding values in a DataFrame

df['numbers'] = round(df['numbers'], 2)
df

  Hello  World  numbers  boolean  null
0     1      2     3.54     True   NaN
1   3.0    4.0     5.01    False   NaN
2  True  False    41.99    False   NaN
3   NaN    NaN    30.46     True   NaN

## Selecting one column

In [348]:
df['numbers']

0     3.54
1     5.01
2    41.99
3    30.46
Name: numbers, dtype: float64

In [349]:
df.numbers

0     3.54
1     5.01
2    41.99
3    30.46
Name: numbers, dtype: float64

### Sample with a large dataset

In [350]:
airlines_df = pd.read_csv('data/airlines_flights_data.csv')
airlines_df.head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [351]:
airlines_df.shape

(300153, 12)

In [352]:
airlines_df[['flight', 'departure_time']]

         flight departure_time
0       SG-8709        Evening
1       SG-8157  Early_Morning
2        I5-764  Early_Morning
3        UK-995        Morning
4        UK-963        Morning
...         ...            ...
300148   UK-822        Morning
300149   UK-826      Afternoon
300150   UK-832  Early_Morning
300151   UK-828  Early_Morning
300152   UK-822        Morning

[300153 rows x 2 columns]

In [353]:
airlines_df.columns

Index(['index', 'airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price'],
      dtype='object')

In [354]:
airlines_df.dtypes

index                 int64
airline              object
flight               object
source_city          object
departure_time       object
stops                object
arrival_time         object
destination_city     object
class                object
duration            float64
days_left             int64
price                 int64
dtype: object

In [355]:
airlines_df['price_per_minute'] = airlines_df['price'] / (airlines_df['duration'] * 60)
airlines_df.head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,price_per_minute
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,45.721966
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,42.582260
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,45.745008
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,44.111111
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,42.596567

In [356]:
np.random.seed(42) # the universal response to everything
airlines_df['random_values'] = np.random.randint(1, 100, size=len(airlines_df))
airlines_df.head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,price_per_minute,random_values
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,45.721966,52
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,42.582260,93
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,45.745008,15
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,44.111111,72
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,42.596567,61

### Adding using the assign method

In [357]:
score1 = np.random.randint(1, 100, size=len(airlines_df))
score2 = np.random.randint(1, 100, size=len(airlines_df))

series1 = pd.Series(score1, name='score1')
series2 = pd.Series(score2, name='score2')
# Assign method allows to add multiple columns at once
airlines_df = airlines_df.assign(score1=series1, score2=series2)
airlines_df.head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,price_per_minute,random_values,score1,score2
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,45.721966,52,15,51
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,42.582260,93,78,34
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,45.745008,15,91,60
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,44.111111,72,39,84
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,42.596567,61,95,69

### Using insert method

In [358]:
airlines_df.insert(0, 'other_new_column', np.random.randint(1, 100, size=len(airlines_df)))
airlines_df.head()

,other_new_column,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,price_per_minute,random_values,score1,score2
0,64,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,45.721966,52,15,51
1,61,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,42.582260,93,78,34
2,66,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,45.745008,15,91,60
3,16,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,44.111111,72,39,84
4,78,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,42.596567,61,95,69

## Math Operations

In [359]:
airlines_df['duration'].sum()

np.float64(3668176.0599999996)

In [360]:
airlines_df['duration'].mean()

np.float64(12.221020812718846)

In [361]:
airlines_df['duration'].median()

11.25

In [362]:
airlines_df['duration'].std()

7.191997238118316

In [363]:
airlines_df['duration'].mean()

np.float64(12.221020812718846)

In [364]:
airlines_df['calculation_result'] = airlines_df['duration'] * airlines_df['price_per_minute']
airlines_df.insert(0, 'scaled', (airlines_df['calculation_result'] - airlines_df['calculation_result'].mean()) / airlines_df['calculation_result'].std())
airlines_df.describe()

,scaled,other_new_column,index,duration,days_left,price,price_per_minute,random_values,score1,score2,calculation_result
count,3.001530e+05,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000,300153.000000
mean,-2.121073e-17,50.063324,150076.000000,12.221021,26.004751,20889.660523,36.257713,49.962959,49.923312,49.999490,348.161009
std,1.000000e+00,28.582024,86646.852011,7.191997,13.561004,22697.767366,45.557214,28.599023,28.593038,28.596999,378.296123
min,-8.716567e-01,1.000000,0.000000,0.830000,1.000000,1105.000000,1.724114,1.000000,1.000000,1.000000,18.416667
25%,-7.096143e-01,25.000000,75038.000000,6.830000,15.000000,4783.000000,7.669630,25.000000,25.000000,25.000000,79.716667
50%,-5.932152e-01,50.000000,150076.000000,11.250000,26.000000,7425.000000,16.304348,50.000000,50.000000,50.000000,123.750000
75%,9.530162e-01,75.000000,225114.000000,16.170000,38.000000,42521.000000,48.214376,75.000000,75.000000,75.000000,708.683333
max,4.501823e+00,99.000000,300152.000000,49.830000,49.000000,123071.000000,474.551282,99.000000,99.000000,99.000000,2051.183333

### Value counts method

In [365]:
airlines_df['duration'].count() == len(airlines_df['duration'])

np.True_

In [366]:
airlines_df['duration'].value_counts()

duration
2.17     4242
2.25     4036
2.75     2879
2.08     2755
2.83     2323
         ...
37.17       1
38.75       1
38.50       1
36.25       1
41.50       1
Name: count, Length: 476, dtype: int64

In [367]:
# By percentage
(airlines_df['duration'].value_counts(normalize=True) * 100).round(5).astype(str) + ' %'

duration
2.17     1.41328 %
2.25     1.34465 %
2.75     0.95918 %
2.08     0.91787 %
2.83     0.77394 %
           ...
37.17    0.00033 %
38.75    0.00033 %
38.50    0.00033 %
36.25    0.00033 %
41.50    0.00033 %
Name: proportion, Length: 476, dtype: object

### Sort a dataframe

In [368]:
airlines_df.sort_values('duration').head()

,scaled,other_new_column,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,price_per_minute,random_values,score1,score2,calculation_result
118982,-0.849672,96,118982,Indigo,6E-357,Bangalore,Night,zero,Night,Chennai,Economy,0.83,42,1604,32.208835,98,72,17,26.733333
118622,-0.849672,19,118622,Indigo,6E-357,Bangalore,Night,zero,Night,Chennai,Economy,0.83,38,1604,32.208835,20,73,98,26.733333
197626,-0.856765,49,197626,Indigo,6E-987,Chennai,Early_Morning,zero,Early_Morning,Bangalore,Economy,0.83,48,1443,28.975904,3,24,20,24.050000
116322,-0.766228,26,116322,Indigo,6E-357,Bangalore,Night,zero,Night,Chennai,Economy,0.83,12,3498,70.240964,59,52,89,58.300000
197628,-0.856765,7,197628,Indigo,6E-6137,Chennai,Morning,zero,Morning,Bangalore,Economy,0.83,48,1443,28.975904,59,15,23,24.050000

In [369]:
airlines_df = airlines_df.sort_values(['price', 'duration'], ascending=True).reset_index(drop=True)
airlines_df.head()

,scaled,other_new_column,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,price_per_minute,random_values,score1,score2,calculation_result
0,-0.871657,35,206273,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,45,1105,18.416667,85,82,18,18.416667
1,-0.871657,36,206352,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,46,1105,18.416667,49,1,61,18.416667
2,-0.871657,4,206432,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,47,1105,18.416667,2,18,45,18.416667
3,-0.871657,63,206509,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,48,1105,18.416667,15,69,50,18.416667
4,-0.871657,64,206589,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,49,1105,18.416667,25,72,70,18.416667

### Create indexes

In [370]:
new_index = np.arange(0, len(airlines_df))
new_index

array([     0,      1,      2, ..., 300150, 300151, 300152])

In [371]:
import random
random.seed(42)
random.shuffle(new_index)

In [372]:
airlines_df['new_index'] = new_index
airlines_df.head()

,scaled,other_new_column,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,price_per_minute,random_values,score1,score2,calculation_result,new_index
0,-0.871657,35,206273,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,45,1105,18.416667,85,82,18,18.416667,153245
1,-0.871657,36,206352,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,46,1105,18.416667,49,1,61,18.416667,187668
2,-0.871657,4,206432,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,47,1105,18.416667,2,18,45,18.416667,66094
3,-0.871657,63,206509,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,48,1105,18.416667,15,69,50,18.416667,163598
4,-0.871657,64,206589,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,49,1105,18.416667,25,72,70,18.416667,259375

In [373]:
# renaming with column
airlines_df['duration'].rename('flight_duration', inplace=True)
airlines_df.head()

,scaled,other_new_column,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,price_per_minute,random_values,score1,score2,calculation_result,new_index
0,-0.871657,35,206273,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,45,1105,18.416667,85,82,18,18.416667,153245
1,-0.871657,36,206352,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,46,1105,18.416667,49,1,61,18.416667,187668
2,-0.871657,4,206432,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,47,1105,18.416667,2,18,45,18.416667,66094
3,-0.871657,63,206509,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,48,1105,18.416667,15,69,50,18.416667,163598
4,-0.871657,64,206589,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,49,1105,18.416667,25,72,70,18.416667,259375

In [374]:
# set the new index
airlines_df.set_index('new_index', inplace=True)
airlines_df.head()

,scaled,other_new_column,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,price_per_minute,random_values,score1,score2,calculation_result
new_index,,,,,,,,,,,,,,,,,,,
153245,-0.871657,35,206273,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,45,1105,18.416667,85,82,18,18.416667
187668,-0.871657,36,206352,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,46,1105,18.416667,49,1,61,18.416667
66094,-0.871657,4,206432,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,47,1105,18.416667,2,18,45,18.416667
163598,-0.871657,63,206509,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,48,1105,18.416667,15,69,50,18.416667
259375,-0.871657,64,206589,GO_FIRST,G8-504,Chennai,Afternoon,zero,Afternoon,Hyderabad,Economy,1.0,49,1105,18.416667,25,72,70,18.416667

In [375]:
airlines_df.sort_index(inplace=True)
airlines_df.head()

,scaled,other_new_column,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,price_per_minute,random_values,score1,score2,calculation_result
new_index,,,,,,,,,,,,,,,,,,,
0,-0.747812,41,74412,GO_FIRST,G8-319,Mumbai,Morning,one,Night,Hyderabad,Economy,11.92,30,3916,5.475391,73,82,79,65.266667
1,-0.469062,67,126334,Vistara,UK-772,Kolkata,Morning,one,Night,Delhi,Economy,11.17,42,10243,15.283497,29,55,78,170.716667
2,-0.750191,18,138181,AirAsia,I5-547,Kolkata,Evening,one,Afternoon,Bangalore,Economy,16.42,21,3862,3.920016,83,26,98,64.366667
3,-0.586210,33,70523,Air_India,AI-809,Mumbai,Morning,one,Morning,Hyderabad,Economy,24.50,3,7584,5.159184,1,39,56,126.400000
4,1.896457,77,270606,Vistara,UK-778,Kolkata,Afternoon,one,Night,Hyderabad,Business,7.58,9,63935,140.578276,12,43,64,1065.583333

In [376]:
airlines_df = airlines_df.rename(columns={
  'flight_duration': 'duration',
  'other_new_column': 'OTC',
  'price_per_minute': 'PPM',
  'score1': 'S1',
  'score2': 'S2'
  }) 
# Renaming with dictionary

In [377]:
# show df
airlines_df.head()

,scaled,OTC,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,PPM,random_values,S1,S2,calculation_result
new_index,,,,,,,,,,,,,,,,,,,
0,-0.747812,41,74412,GO_FIRST,G8-319,Mumbai,Morning,one,Night,Hyderabad,Economy,11.92,30,3916,5.475391,73,82,79,65.266667
1,-0.469062,67,126334,Vistara,UK-772,Kolkata,Morning,one,Night,Delhi,Economy,11.17,42,10243,15.283497,29,55,78,170.716667
2,-0.750191,18,138181,AirAsia,I5-547,Kolkata,Evening,one,Afternoon,Bangalore,Economy,16.42,21,3862,3.920016,83,26,98,64.366667
3,-0.586210,33,70523,Air_India,AI-809,Mumbai,Morning,one,Morning,Hyderabad,Economy,24.50,3,7584,5.159184,1,39,56,126.400000
4,1.896457,77,270606,Vistara,UK-778,Kolkata,Afternoon,one,Night,Hyderabad,Business,7.58,9,63935,140.578276,12,43,64,1065.583333