# Web Scraping Project With Python and Pandas

- Target website: https://www.football-data.co.uk/data.php

- Data to scrape: Historical football match results

In [2]:
import pandas as pd
import numpy as np
import requests
import random
import io
import time

In [3]:

url = 'https://www.football-data.co.uk/mmz4281/2425/E0.csv'
header = {   'User-Agent': 'Mozilla/5.0'}
retry_delay = 1  # seconds
while True:
  try:
    
      response = requests.get(url, headers=header)
      s24_25_premier_league_df = pd.read_csv(io.StringIO(response.text))
      break
  except requests.exceptions.RequestException as e:
    time.sleep(retry_delay)
    continue

s24_25_premier_league_df.head()

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10

In [4]:
s24_25_premier_league_df.shape

(380, 120)

In [5]:
# Rename columns
columns_to_rename = {
    'ï»¿Div	': 'Division',
    'FTHG': 'Home Goals',
    'FTAG': 'Away Goals',
    'FTR': 'Full Time Result',
    'HTHG': 'Half Time Home Goals',
    'HTAG': 'Half Time Away Goals',
    'HTR': 'Half Time Result',
    'HS': 'Home Shots',
}
s24_25_premier_league_df = s24_25_premier_league_df.rename(columns=columns_to_rename)
s24_25_premier_league_df.head()

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,Home Goals,Away Goals,Full Time Result,Half Time Home Goals,Half Time Away Goals,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10

In [6]:
s24_25_premier_league_df.columns

Index(['ï»¿Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'Home Goals',
       'Away Goals', 'Full Time Result', 'Half Time Home Goals',
       'Half Time Away Goals',
       ...
       'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA',
       'AvgCAHH', 'AvgCAHA', 'BFECAHH', 'BFECAHA'],
      dtype='object', length=120)

## Extracting multiple CSV files by finding a pattern in the URL

https://www.football-data.co.uk/mmz4281/2425/E0.csv

https://www.football-data.co.uk/mmz4281/2425/E1.csv

https://www.football-data.co.uk/mmz4281/2223/E1.csv

In [7]:
def extract_info_from_url(url) -> pd.DataFrame:
  url = 'https://www.football-data.co.uk/mmz4281/2425/E0.csv'
  headers = {
      'User-Agent': 'Mozilla/5.0',
      'Accept': 'text/csv,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
      'Accept-Language': 'en-US,en;q=0.5',
      'Connection': 'keep-alive',
      'Referer': 'https://www.football-data.co.uk/data.php',
      'DNT': '1',
      'Upgrade-Insecure-Requests': '1'
  }

  while True:
    try:
      
        response = requests.get(url, headers=headers)
        df = pd.read_csv(io.StringIO(response.text))

        return df
    
    except requests.exceptions.RequestException as e:

      continue

In [8]:
# A non existing URL to test the function
df = extract_info_from_url('https://www.football-data.co.uk/mmz4281/2425/E1.csv')
# there is sent data but it is the default E0.csv
df

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

In [26]:
today_year = int(time.strftime('%Y'))
dfs: dict[str, pd.DataFrame] = {}
for i in range(10): # 10 years back
    j = 0
    error_count = 0
    today_year_2_digit = str(today_year - i - 1)[2:]
    last_year_2_digit = str(today_year - i)[2:]
    year_str = f'{today_year_2_digit}{last_year_2_digit}'
    while True:
        url = f'https://www.football-data.co.uk/mmz4281/{year_str}/E{j}.csv'
        extracted_df = extract_info_from_url(url)
        j += 1
        print(extracted_df['ï»¿Div'][0], f'E{j - 1}')
        if extracted_df['ï»¿Div'][0] != f'E{j - 1}':
            print(f'No more data for {year_str} E{j}')
            break
        else:
            dfs[year_str] = extracted_df

E0 E0
E0 E1
No more data for 2425 E2
E0 E0
E0 E1
No more data for 2324 E2
E0 E0
E0 E1
No more data for 2223 E2
E0 E0
E0 E1
No more data for 2122 E2
E0 E0
E0 E1
No more data for 2021 E2
E0 E0
E0 E1
No more data for 1920 E2
E0 E0
E0 E1
No more data for 1819 E2
E0 E0
E0 E1
No more data for 1718 E2
E0 E0
E0 E1
No more data for 1617 E2
E0 E0
E0 E1
No more data for 1516 E2

In [14]:
len(dfs)

10

In [16]:
dfs['2425'].head()

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10

In [41]:
import os
import json
print(type(dfs))
data: dict[str, dict] = {}
for dataframe in dfs.keys():
  dfs[dataframe].fillna(0, inplace=True)
  data[dataframe] = dfs[dataframe].to_dict()

# json.dumps(dfs[dataframe], indent=4)
path: str = 'data/web_scraping_data.json'
with open(path, 'w') as f:
    json.dump(data, f, indent=2)
storage = os.path.getsize(path) / 1e6
print(f'File {path.split('/')[-1]} wrote with {round(storage)} MB')

<class 'dict'>
File web_scraping_data.json wrote with 8 MB

In [42]:
# We can also concat the dfs into a single
df_list:list[pd.DataFrame] = []
for key in dfs.keys():
  df_list.append(dfs[key])
single_df = pd.concat(df_list)
single_df

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10